#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
pandoc --pdf-engine=lualatex --filter=pandoc-eqnos --filter=pandoc-fignos --template="${DIR}/templateR1.tex" -o "${DIR}/output/${1}.pdf" "${DIR}/${1}/DOC.md"
